version: "1.0"
services:
  spring-docker-demo:
    container_name: inventory-management
    image: inventory-management
    ports:
      - "8080:8090"
  db:
    container_name: postgres_c
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  volumes:
    db:
      driver: local